backup_partition.py: Rewrite in Python!

diff --git a/sysadmin/a-l/backup-root-sata2 b/sysadmin/a-l/backup-root-sata2
--- a/sysadmin/a-l/backup-root-sata2
+++ b/sysadmin/a-l/backup-root-sata2
@@ -1,15 +1,16 @@
 #!/bin/bash
 # Back up a root partition to another partition on another SATA SSD.
 
-script="$(dirname $(realpath "$0"))/../backup-partition"
+script="$(dirname $(realpath "$0"))/../backup_partition.py"
 if [ ! -e "$script" ]; then
-    echo "Could not find backup-partition script" >&2; exit 1
+    echo "Could not find backup_partition.py script" >&2; exit 1
 fi
 
-verbose=
+passthrough=()
 while [ "$#" -gt 0 ]; do
     case "$1" in
-        -v|--verbose)  verbose="$1"; shift ;;
+        -v|--verbose)  passthrough+=("--verbose"); shift ;;
+        -n|--dry-run)  passthrough+=("--dry-run"); shift ;;
         -*)  echo "Unknown flag '$1'" 2>&1; exit 1 ;;
         *)   echo "Unknown argument '$1'" 2>&1; exit 1 ;;
     esac
@@ -19,8 +20,10 @@ if [ "`id -u`" != 0 ]; then
     echo "Warning: not root.  (Try with ssudo?)" >&2
 fi
 
-"$script" $verbose --write-times /common/backups/last_backup.root_sata2 \
+"$script" "${passthrough[@]}" \
+          --write-times /common/backups/last_backup.root_sata2 \
+          -X .cache -X .gvfs \
           --root \
-          -X .cache -X .gvfs LABEL="root" LABEL="sata2_root" \
-          --data \
+          LABEL="root" LABEL="sata2_root" \
+          --efi \
           LABEL="EFI_SYS" LABEL="SATA2EFISYS"
